spring:
  datasource:
    url: jdbc:h2:./devb
    username: sa
  jpa:
    hibernate:
      ddl-auto: update 
      

 
  properties:
      javax:
        persistence:
          validation:
            mode: none